name: default-branch-push

concurrency:
  group: default-branch-push
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  format-files:
    uses: ./.github/workflows/format-files.yml

  release-please:
    if: always()
    runs-on: ubuntu-latest
    needs: format-files
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest

      - name: Generate Summary of `Release Please` Run
        env:
          RP_OUTPUT: ${{ toJSON(steps.release.outputs) }}
        run: printf '```json\n%s\n```' "$RP_OUTPUT" >> "$GITHUB_STEP_SUMMARY"
